[package]
name = "har"
version = "0.7.1"
authors = ["Sebastian Mandrean <sebastian.mandrean@gmail.com>"]
edition = "2018"
description = "A HTTP Archive format (HAR) serialization & deserialization library."
license = "MIT"
repository = "https://github.com/mandrean/har-rs"
documentation = "https://docs.rs/har"
readme = "README.md"
keywords = ["har", "serialization", "deserialization", "json", "yaml"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
thiserror = "1.0"

[dependencies.serde_with]
version = "1.6"
features = ["serde_with_macros"]

[dev-dependencies]
glob = "0.3.0"
